### ISSUE TITLE
Auto conversion of block/item unlocal names?

### ISSUE THREAD

**Issue by williewillus** [ichttt/MCLang2Json#1]
See details (2nd/3rd bullet under lang changes): https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a

Big things being the prefix for blocks is now "block" not "tile", and both blocks and items lose the ".name" suffix. The middle part also becomes a registry name but that's not really scriptable.

Maybe automatically rename tile. to block. and strip .name if it began with item. or tile. as well?

**Comment by ichttt** [comment]
Sure, good idea, thanks for the useful gist!

**Comment by ichttt** [comment]
Resolved in cd0484081e1cdb3391e1853cba02492e83eaac5b

**Comment by williewillus** [comment]
@ichttt turns out I read the snapshot code incorrectly, the new names are `block.minecraft.dirt`, not `block.minecraft:dirt` (colons in the registry name are converted to periods)

sorry for the misinformation! :P
