### ISSUE TITLE
Comments are not supported

### ISSUE THREAD

**Issue by drcrazy** [ichttt/MCLang2Json#2]
v 1.1 doesn't support comments in lang file. 
It throws an error that lang file is not lang file as soon as it encounter comment in lang file. 

Maybe it will be better to silently skip comments

**Comment by ichttt** [comment]
Huh, didn't know the MC lang format actually has comments... Well, as json does not support any comments, I think they should be stripped. Thanks for the report!

**Comment by ichttt** [comment]
closed in b82971de0164918a85ef154cf2eae56b9070869d (binary 1.2)

**Comment by thecatcore** [comment]
I have an error because .lang files can also use "//" to start a comment and not only "#"
