### ISSUE TITLE
Text is small on screens with a large resolution

### ISSUE THREAD

**Issue by Iuhegi** [ichttt/MCLang2Json#3]
I ran this on a Surface book 2 and it looked like this
![Screenshot](https://user-images.githubusercontent.com/7998611/35193380-774aa9b8-fe99-11e7-9d8c-ccb02c0f0b37.png)
Maybe you could change the size of the text based on the resolution of the screen, or based on the OS's default zoom (on Windows 10, I have that set to 200% to make most apps readable)

**Comment by ichttt** [comment]
It seems to be a known swing bug, see https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display. I'll just increase the default font size
